/**
 * Type stubs for the video_sync WASM package generated by wasm-pack.
 * The actual .wasm and .js glue are produced by `wasm-pack build --target web`
 * at build time and are not committed to the repository.
 *
 * These stubs allow `tsc --noEmit` to pass in CI without running wasm-pack,
 * while preserving full type safety in the surrounding TypeScript code.
 */

export default function init(module?: WebAssembly.Module | BufferSource | URL): Promise<void>;

export class WasmVideoRecord {
  /** Construct a new video record from an IndexVideoCmd JSON string. */
  constructor(cmd: string);
  /** Deserialise an existing record snapshot. */
  static fromJson(json: string): WasmVideoRecord;
  id(): string;
  to_json(): string;
  approve(cmd: string): string;
  mark_in_scope(cmd: string): string;
  skip(cmd: string): string;
  abandon(cmd: string): string;
  mark_to_retry(cmd: string): string;
  request_publish(cmd: string): string;
  mark_published(cmd: string): string;
  mark_failed(cmd: string): string;
  add_note(cmd: string): string;
  update_metadata(cmd: string): string;
  add_location(cmd: string): string;
  remove_location(cmd: string): string;
  update_location_status(cmd: string): string;
  link_upstream(cmd: string): string;
  unlink_upstream(cmd: string): string;
}
